In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.linear_model import LinearRegression
sb.set()
import numpy as np

In [2]:
data = pd.read_csv('/home/rshubham/STUDY/udemy_ml/S34_L213/original.csv')

In [5]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [8]:
y = data['GPA']
x = data[['SAT', 'Rand 1,2,3']]
x.shape

(84, 2)

In [9]:
reg = LinearRegression()

In [10]:
reg.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
reg.score(x, y)

0.4066811952814285

In [12]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [13]:
reg.intercept_

0.29603261264909486

# Adjusted R-Squared
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$
#### n = number of observations (as in this case we have 84 observations)
#### p = number of predictors (as we have 2 predictors in this case)

In [14]:
x.shape

(84, 2)

In [15]:
r1 = reg.score(x, y)

In [16]:
n = x.shape[0]
p = x.shape[1]

In [18]:
r_adjusted = (1 - (((n-1)/(n-p-1))*(1 - r1)))
r_adjusted

0.39203134825134023

# Feature Selection

In [19]:
from sklearn.feature_selection import f_regression

In [20]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [22]:
p_value = f_regression(x, y)[1]

In [23]:
p_value.round(3)

array([0.   , 0.676])

# Create a Summary Table

In [26]:
reg_summary = pd.DataFrame(data = x.columns.values, columns = ['Features'])

In [27]:
reg_summary['coefficient'] = reg.coef_
reg_summary['p-value'] = p_value.round(3)

In [28]:
reg_summary

Features  coefficient  p-value
0         SAT     0.001654    0.000
1  Rand 1,2,3    -0.008270    0.676