# Multiple Linear Regression with sklearn - Exercise Solution

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression (similar to the one in the lecture), using the new data. 

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

Good luck!

## Import the relevant libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.linear_model import LinearRegression
sb.set()
import numpy as np

## Load the data

In [2]:
data = pd.read_csv('real_estate_price_size_year.csv')

In [3]:
data.head()

price     size  year
0  234314.144   643.09  2015
1  228581.528   656.22  2009
2  281626.336   487.29  2018
3  401255.608  1504.75  2015
4  458674.256  1275.46  2009

## Create the regression

### Declare the dependent and the independent variables

In [4]:
y = data['price']
x = data[['size', 'year']]

### Regression

In [5]:
reg = LinearRegression()
reg.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Find the intercept

In [7]:
reg.intercept_

-5772267.017463278

### Find the coefficients

In [8]:
reg.coef_

array([ 227.70085401, 2916.78532684])

### Calculate the R-squared

In [10]:
reg.score(x, y)

0.7764803683276793

### Calculate the Adjusted R-squared

In [12]:
r1 = reg.score(x, y)
n = x.shape[0]
p = x.shape[1]

In [13]:
adj_r = 1 - (1-r1)*((n-1)/(n-p-1))
adj_r

0.77187171612825

### Compare the R-squared and the Adjusted R-squared

It seems the the R-squared is only slightly larger than the Adjusted R-squared, implying that we were not penalized a lot for the inclusion of 2 independent variables.

### Compare the Adjusted R-squared with the R-squared of the simple linear regression

Comparing the Adjusted R-squared with the R-squared of the simple linear regression (when only 'size' was used - a couple of lectures ago), we realize that 'Year' is not bringing too much value to the result.

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [17]:
new_data = pd.DataFrame({'size' : [750], 'year' : [2009]})
new_data['predicted value'] = reg.predict(new_data)
new_data

size  year  predicted value
0   750  2009     258330.34466

### Calculate the univariate p-values of the variables

In [18]:
from sklearn.feature_selection import f_regression

In [19]:
f_regression(x, y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [20]:
p_value = f_regression(x, y)[1]

In [24]:
p_value.round(3)

array([0.   , 0.357])

### Create a summary table with your findings

In [22]:
summary = pd.DataFrame(data = x.columns.values, columns = ['features'])
summary['coefficient'] = reg.coef_
summary['p_value'] = p_value.round(3)
summary

features  coefficient  p_value
0     size   227.700854    0.000
1     year  2916.785327    0.357

It seems that 'Year' is not event significant, therefore we should remove it from the model.